### PR TITLE
Fix CHLCC Erin Screen Smash Anim

### LINKED ISSUE #361: Erin Smashing Animation

### PR DESCRIPTION
**Pull request by Gunoshozo**

### CODE REVIEW

File: src/character2d.cpp [hunk 1]
```diff
@@ -434,8 +434,8 @@ void Character2D::Render(const int layer) {
     }
 
   } else {
-    const glm::mat4 transformation =
-        TransformationMatrix({0.0f, 0.0f}, Scale, glm::vec3(0.0f), Rotation);
+    const glm::mat4 transformation = TransformationMatrix(
+        Position, Scale, glm::vec3(0.0f), Rotation);
```
Comment (PringlesGang) [inline src/character2d.cpp]: In that case the rotation origin is probs also Position. Can't think of many scenes that rotate a character tho, to test
